### ISSUE TITLE
how to fix it?

### ISSUE THREAD

**Issue by iKingFe** [arcadiadevs/gensplus-issues#34]
[06:30:01 WARN]: [GensPlus] Task #165123 for GensPlus v1.3.1-beta3 generated an exception
java.util.NoSuchElementException: No value present
        at java.util.Optional.orElseThrow(Optional.java:377) ~[?:?]
        at xyz.arcadiadevs.gensplus.models.LocationsData$GeneratorLocation.getWorld(:241) ~[GensPlus.jar:?]
        at xyz.arcadiadevs.gensplus.models.LocationsData$GeneratorLocation.getCenter(:370) ~[GensPlus.jar:?]
        at xyz.arcadiadevs.gensplus.models.LocationsData$GeneratorLocation.spawn(:287) ~[GensPlus.jar:?]
        at xyz.arcadiadevs.gensplus.tasks.SpawnerTask.lambda$run$1(:64) ~[GensPlus.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.4.jar:git-Purpur-1985]

**Comment by OpenSource03** [comment]
We need more info on how to reproduce this issue and when does it happen. It would be great if you could send us more info. As soon as you do, we will reopen the issue.
