### ISSUE TITLE
CONSOLE SPAMS

### ISSUE THREAD

**Issue by Y3ko** [arcadiadevs/gensplus-issues#38]
[21:46:07 WARN]: [GensPlus] Plugin GensPlus v1.3.3 generated an exception while executing task 135
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
        at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
        at xyz.arcadiadevs.gensplus.tasks.CleanupTask.run(:29) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[lightspigot-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:46:08 WARN]: [GensPlus] Plugin GensPlus v1.3.3 generated an exception while executing task 135
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
        at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
        at xyz.arcadiadevs.gensplus.tasks.CleanupTask.run(:29) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[lightspigot-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        
        
        [10:34:00] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to GensPlus v1.3.4
java.lang.IllegalArgumentException: Unsupported material with no data value: CHERRY_TRAPDOOR
    at com.cryptomorin.xseries.XMaterial.lambda$matchXMaterial$0(XMaterial.java:1691) ~[GensPlus.jar:?]
    at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
    at com.cryptomorin.xseries.XMaterial.matchXMaterial(XMaterial.java:1691) ~[GensPlus.jar:?]
    at xyz.arcadiadevs.gensplus.events.SmeltItem.onCampfireClick(:191) ~[GensPlus.jar:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor726.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[lightspigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[lightspigot-api-1.20.1-R0.1-SNAPSHOT.jar:git-LightSpigot-"ad20ecf"]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[lightspigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[lightspigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:591) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:537) ~[?:?]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2018) ~[?:?]
    at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
    at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:9) ~[?:?]
    at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
    at net.minecraft.server.TickTask.run(TickTask.java:18) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
    at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
    at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1352) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at net.minecraft.server.MinecraftServer.wrapRunnable(MinecraftServer.java:200) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
    at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1329) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1322) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
    at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1300) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:41:26] [Server thread/ERROR]: Could not pass event InventoryClickEvent to GensPlus v1.3.4
java.lang.IllegalArgumentException: Object provided must be of type ItemStack, Entity, Block, or NBTCompound!
    at io.github.bananapuncher714.nbteditor.NBTEditor.getValue(NBTEditor.java:952) ~[GensPlus.jar:?]
    at io.github.bananapuncher714.nbteditor.NBTEditor.contains(NBTEditor.java:1152) ~[GensPlus.jar:?]
    at xyz.arcadiadevs.gensplus.events.SmeltItem.isGensItem(:212) ~[GensPlus.jar:?]
    at xyz.arcadiadevs.gensplus.events.SmeltItem.onInventoryClick(:42) ~[GensPlus.jar:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor728.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[lightspigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[lightspigot-api-1.20.1-R0.1-SNAPSHOT.jar:git-LightSpigot-"ad20ecf"]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[lightspigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[lightspigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3261) ~[?:?]
    at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
    at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
    at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
    at net.minecraft.server.TickTask.run(TickTask.java:18) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
    at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
    at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1352) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at net.minecraft.server.MinecraftServer.wrapRunnable(MinecraftServer.java:200) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
    at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1329) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1322) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
    at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1300) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
    
    01:32:50] [Server thread/ERROR]: Could not pass event InventoryClickEvent to GensPlus v1.3.3
java.lang.IllegalArgumentException: Object provided must be of type ItemStack, Entity, Block, or NBTCompound!
    at io.github.bananapuncher714.nbteditor.NBTEditor.getValue(NBTEditor.java:952) ~[GensPlus.jar:?]
    at io.github.bananapuncher714.nbteditor.NBTEditor.contains(NBTEditor.java:1152) ~[GensPlus.jar:?]
    at xyz.arcadiadevs.gensplus.events.SmeltItem.isGensItem(:212) ~[GensPlus.jar:?]
    at xyz.arcadiadevs.gensplus.events.SmeltItem.onInventoryClick(:42) ~[GensPlus.jar:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor718.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[lightspigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[lightspigot-api-1.20.1-R0.1-SNAPSHOT.jar:git-LightSpigot-"ad20ecf"]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[lightspigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[lightspigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3261) ~[?:?]
    at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
    at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
    at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
    at net.minecraft.server.TickTask.run(TickTask.java:18) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
    at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
    at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1352) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at net.minecraft.server.MinecraftServer.wrapRunnable(MinecraftServer.java:200) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
    at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1329) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1322) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
    at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1300) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by OpenSource03** [comment]
Fixed in v1.3.6
