### ISSUE TITLE
Paper Spigot 1.20.5 Internals Mappings Update

### ISSUE THREAD

**Issue by iTemmy** [arcadiadevs/gensplus-issues#54]
**Describe the bug**
The plugin is unable to be Remapped by Paper Spigot after the mappings update and will produce the below error when the server attempts to remap the plugin.

**To Reproduce**
1. Install plugin and dependencies on 1.20.6 paper server
2. Start server 
3. See error

**Config**
```
N/A Doesn't even generate config
```

**Expected behavior**
The plugin to start

**Screenshots**
```
[11:39:58 INFO]: [PluginRemapper] Remapping plugin 'plugins/GensPlus-v1.5.4.jar'...
[11:39:59 ERROR]: [PluginRemapper] Encountered exception remapping plugins
java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to remap plugin jar 'plugins/GensPlus-v1.5.4.jar'
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.RuntimeException: Failed to remap plugin jar 'plugins/GensPlus-v1.5.4.jar'
        at io.papermc.paper.pluginremap.PluginRemapper.lambda$remap$7(PluginRemapper.java:358) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        ... 4 more
Caused by: java.lang.RuntimeException: Failed to execute task .dummy.class
        at net.neoforged.art.internal.AsyncHelper.invokeAll(AsyncHelper.java:56) ~[AutoRenamingTool-2.0.3.jar:?]
        at net.neoforged.art.internal.AsyncHelper.invokeAll(AsyncHelper.java:41) ~[AutoRenamingTool-2.0.3.jar:?]
        at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:184) ~[purpur-1.20.6.jar:?]
        at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:95) ~[purpur-1.20.6.jar:?]
        at io.papermc.paper.pluginremap.PluginRemapper.lambda$remap$7(PluginRemapper.java:355) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        ... 4 more
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Invalid descriptor: (/)L/;
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
        at net.neoforged.art.internal.AsyncHelper.invokeAll(AsyncHelper.java:52) ~[AutoRenamingTool-2.0.3.jar:?]
        at net.neoforged.art.internal.AsyncHelper.invokeAll(AsyncHelper.java:41) ~[AutoRenamingTool-2.0.3.jar:?]
        at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:184) ~[purpur-1.20.6.jar:?]
        at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:95) ~[purpur-1.20.6.jar:?]
        at io.papermc.paper.pluginremap.PluginRemapper.lambda$remap$7(PluginRemapper.java:355) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        ... 4 more
Caused by: java.lang.IllegalArgumentException: Invalid descriptor: (/)L/;
        at org.objectweb.asm.Type.getTypeInternal(Type.java:429) ~[asm-9.7.jar:9.7]
        at org.objectweb.asm.Type.getArgumentTypes(Type.java:317) ~[asm-9.7.jar:9.7]
        at org.objectweb.asm.commons.Remapper.mapMethodDesc(Remapper.java:139) ~[asm-commons-9.7.jar:9.7]
        at net.neoforged.art.internal.EnhancedClassRemapper.visitMethod(EnhancedClassRemapper.java:35) ~[AutoRenamingTool-2.0.3.jar:?]
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1354) ~[asm-9.7.jar:9.7]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:745) ~[asm-9.7.jar:9.7]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:425) ~[asm-9.7.jar:9.7]
        at net.neoforged.art.internal.RenamingTransformer.process(RenamingTransformer.java:50) ~[AutoRenamingTool-2.0.3.jar:?]
        at net.neoforged.art.internal.EntryImpl$ClassEntry.process(EntryImpl.java:58) ~[AutoRenamingTool-2.0.3.jar:?]
        at net.neoforged.art.internal.EntryImpl$ClassEntry.process(EntryImpl.java:36) ~[AutoRenamingTool-2.0.3.jar:?]
        at net.neoforged.art.internal.RenamerImpl.processEntry(RenamerImpl.java:288) ~[purpur-1.20.6.jar:?]
        at net.neoforged.art.internal.AsyncHelper.lambda$null$2(AsyncHelper.java:40) ~[AutoRenamingTool-2.0.3.jar:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        ... 3 more
```

**Additional info (please complete the following information):**
 - Your GensPlus version: 1.5.4
 - Spigot Version:  paper version 1.20.6-148-ver/1.20.6@20f5165
 - Using ViaVersion/ProtocolSupport: no
 - Your MC version: 1.20.6

**Comment by Marko675** [comment]
The issue has been resolved in the latest build, which we will publish today.
